### ISSUE TITLE
Network picker runs twice

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/WMIControl#42]
![image](https://cloud.githubusercontent.com/assets/9100169/25421297/fe23b564-2a10-11e7-9ad9-8fae67cb0507.png)

This is due to the precompiled arguments in the network file (I'm very tired. Probably using the wrong terminology)

**Comment by crutchcorn** [comment]
Honestly, the network picker is going about things the wrong way. What should be done is to store the information in the newly created JSON file. Check if there is a default and set it permanently. I am currently looking for unique identifiers in WMI for network devices so I can see how viable this option is

**Comment by crutchcorn** [comment]
I'm kinda forgetting a pretty viable method of unique identification for network devices:
MACAddress

**Comment by typedrat** [comment]
@crutchcorn You can't trust MAC addresses to be unique, not fully. A lot of poor quality Chinese stuff will use one MAC over and over and over, instead of following the rules.

**Comment by crutchcorn** [comment]
And yes, I get that, but:
1) I can't exactly be faulted for hardware issues can I?
2) Windows tends not to handle unique perminance of identifying hardware
(you know, because of the reason you mentioned)
3) I just need the code working in general right now

**Comment by crutchcorn** [comment]
Speaking of which, the code is finished. I'll have it up sometime this
weekend most likely. Fairly simple implementation

**Comment by typedrat** [comment]
Wasn't even "don't do it", more of a note to make sure that it's on hand if a problem like that does show up.

**Comment by crutchcorn** [comment]
I gotcha. I'll be sure to document
